language: python
python:
  - "3.9"

env:
  - DOCKER_COMPOSE_VERSION=1.26.2

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - echo https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt update
  - sudo apt install -y postgresql-client
  - docker-compose -f docker-compose-dev.yml up -d

install:
  - pip install --no-cache-dir pipenv && pipenv install --dev --deploy
  - pip install coveralls

script:
  - psql -h "localhost" -U "postgres" -f travis.sql
  - export DJANGO_SETTINGS_MODULE=wamytmsite.settings.test
  - cd src
  - ./manage.py collectstatic
  - coverage run --source='.' manage.py test wamytmapp

after_success:
  - coveralls
