# Build a fresh container image of korporator and run it 
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD:PEqmZ9dt
      - POSTGRES_USER:postgres
    volumes: 
      - wamytm-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  keycloak:
    image: jboss/keycloak
    environment: 
      - KEYCLOAK_USER=k-admin
      - KEYCLOAK_PASSWORD=s3c4stroNG
      - KEYCLOAK_IMPORT=/tmp/wamytm-realm.json
    volumes:
      - ./realm.json:/tmp/wamytm-realm.json
    ports:
      - 8443:8443

  korporator:
    image: erikwegner/korporator
    build: .
    environment:
      - SECRET_KEY=dfkjdhf8743hfsdhfksjh932
      - WAMYTM_DEBUG=True
      - WAMYTM_DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - WAMYTM_DATABASE_HOST=db
      - WAMYTM_DATABASE_NAME=wamytmdb
      - WAMYTM_DATABASE_USERNAME=wamytm
      - WAMYTM_DATABASE_PASSWORD=Stw9nUvm
      - WAMYTM_KEYCLOAK_CLIENT_ID=wamytm
      - WAMYTM_KEYCLOAK_CLIENT_SECRET=6fd1a212-deed-450c-b28d-3170a0c6102c
      - WAMYTM_KEYCLOAK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArGuiHOzKTL9l0Djtx/TZxlFQdqLMtxKHn6l0elC4+sE91LlbjqpbiTUDwAPIPEZ9JDFuLwf/fkpr82zN9eXOsqhZ2Sbd6WODWfgmyiNI8Dcq0/H4tSs2CwvWvXo+oPJWKZsOyldaLGUKxk2BzobF8x4NXdZD6GaqebcORYLUL/MJ6FT8DxQaqsXrImBJ1pAov17ExLD9bIKZBxvqAYQn/uvNk8/9u4LUSWEx3sEo+6/a2Ddrg6/tEfb0JIVTjn8PU9Tz0zVw/19flnvm8yAo6BMHJ9ncN2BTtqI7XlIdA4FWeosAeu8y7BAMPv/itP/Pqdx9H1Ep2E48H6DkrExNHQIDAQAB
      - WAMYTM_KEYCLOAK_AUTH_URL=https://127.0.0.1:8443/auth/realms/wamytmdev/protocol/openid-connect/auth
      - WAMYTM_KEYCLOAK_TOKEN_URL=https://keycloak:8443/auth/realms/wamytmdev/protocol/openid-connect/token
      - WAMYTM_KEYCLOAK_VERIFY_SSL=False
    ports:
      - 8000:8000

volumes:
  wamytm-db:
    driver: local
