# Setup required services for local development
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=PEqmZ9dt
      - POSTGRES_USER=postgres
    volumes: 
      - wamytm-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 5480:8080

  keycloak:
    image: jboss/keycloak
    environment: 
      - KEYCLOAK_USER=k-admin
      - KEYCLOAK_PASSWORD=s3c4stroNG
      - KEYCLOAK_IMPORT=/tmp/wamytm-realm.json
    volumes:
      - ./realm.json:/tmp/wamytm-realm.json
    ports:
      - 8443:8443

volumes:
  wamytm-db:
    driver: local
