# Setup required services for local development
version: '3'

services:
  db:
    image: postgres
    container_name: postgresql
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=PEqmZ9dt
      - POSTGRES_USER=postgres
    volumes: 
      - wamytm-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  #adminer:
  #  image: adminer
  #  container_name: adminer
  #  ports:
  #    - 5480:8080

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment: 
      - KEYCLOAK_USER=k-admin
      - KEYCLOAK_PASSWORD=s3c4stroNG
      - KEYCLOAK_IMPORT=/tmp/wamytm-realm.json
      - ROOT_LOGLEVEL=ALL
    volumes:
      - ./realm.json:/tmp/wamytm-realm.json
    ports:
      - 8443:8443

volumes:
  wamytm-db:
    driver: local
