# Generated by Django 5.2.9 on 2025-12-30 12:08

import django.core.serializers.json
import django.db.models.deletion
import django_prometheus.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mv_odb_org',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mv_odb_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MV_OMS_DATEN',
            fields=[
                ('mit_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mit_name_akt', models.CharField(max_length=255, null=True)),
                ('mit_vorname', models.CharField(max_length=255, null=True)),
                ('mit_austritt', models.DateField(blank=True, null=True)),
                ('kid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'mv_oms_daten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ODB_MITARBEITER2STRUKT',
            fields=[
                ('m2o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m2o_mit_id', models.BigIntegerField(null=True)),
                ('m2o_org_id', models.IntegerField(null=True)),
                ('m2o_von', models.DateField(blank=True, null=True)),
                ('m2o_bis', models.DateField(blank=True, null=True)),
                ('m2o_typ', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'odb_mitarbeiter2strukt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ODB_ORG',
            fields=[
                ('org_id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255, null=True)),
                ('org_kbez', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'odb_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ODB_STRUKT',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_parent_id', models.IntegerField(null=True)),
                ('m_org_id', models.IntegerField(null=True)),
                ('m_von', models.DateField(blank=True, null=True)),
                ('m_bis', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'odb_strukt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.DateField(verbose_name='Start')),
                ('bis', models.DateField(blank=True, verbose_name='End')),
                ('kind', models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('m', 'mobile')], default='a', max_length=1, verbose_name='Kind of time range')),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'verbose_name': 'time range',
                'verbose_name_plural': 'time ranges',
                'managed': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('timerange'), models.Model),
        ),
        migrations.CreateModel(
            name='KIND',
            fields=[
                ('kind', models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('m', 'mobile')], max_length=1, primary_key=True, serialize=False)),
                ('wertung', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orgs4wamytm',
            fields=[
                ('m_org', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wamytmapp.odb_org')),
            ],
        ),
        migrations.CreateModel(
            name='AllDayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='description')),
                ('day', models.DateField(verbose_name='day')),
            ],
            options={
                'verbose_name': 'all day event',
                'verbose_name_plural': 'all day events',
                'indexes': [models.Index(fields=['day'], name='wamytmapp_a_day_12b20a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTimeRange',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('von', models.DateField(verbose_name='Start')),
                ('bis', models.DateField(blank=True, verbose_name='End')),
                ('kind', models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('m', 'mobile')], default='a', max_length=1, verbose_name='Kind of time range')),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wamytmapp.odb_org', verbose_name='Organizational unit')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical time range',
                'verbose_name_plural': 'historical time ranges',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mit_id', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.orgunit')),
            ],
            options={
                'verbose_name': 'Organizational unit',
                'verbose_name_plural': 'Organizational units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnitDelegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wamytmapp.odb_org')),
                ('orgunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wamytmapp.orgunit', verbose_name='Organizational unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Delegate for an organizational unit',
                'verbose_name_plural': 'Delegate for organizational units',
                'permissions': [('assign_delegates', 'Can assign delegates')],
            },
        ),
        migrations.AddField(
            model_name='orgunit',
            name='delegates',
            field=models.ManyToManyField(through='wamytmapp.OrgUnitDelegate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='virtualteam',
            fields=[
                ('vt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vt_name', models.TextField()),
                ('is_privat', models.BooleanField(default=False)),
                ('vt_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.virtualteam')),
            ],
        ),
        migrations.CreateModel(
            name='ma2vt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.virtualteam')),
            ],
        ),
    ]
