# Generated by Django 2.2.7 on 2019-12-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('day', models.DateField()),
            ],
        ),
    ]
