# Generated by Django 3.0.4 on 2020-03-16 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wamytmapp', '0002_alldayevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldayevent',
            options={'verbose_name': 'all day event', 'verbose_name_plural': 'all day events'},
        ),
        migrations.AlterModelOptions(
            name='orgunit',
            options={'verbose_name': 'Organizational unit', 'verbose_name_plural': 'Organizational units'},
        ),
        migrations.AlterModelOptions(
            name='timerange',
            options={'verbose_name': 'time range', 'verbose_name_plural': 'time ranges'},
        ),
        migrations.AlterField(
            model_name='alldayevent',
            name='day',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='alldayevent',
            name='description',
            field=models.TextField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='end',
            field=models.DateField(blank=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='kind',
            field=models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('m', 'mobile')], default='a', max_length=1, verbose_name='Kind of time range'),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='orgunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.OrgUnit', verbose_name='Organizational unit'),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='start',
            field=models.DateField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
