# Generated by Django 3.0.4 on 2020-03-29 09:58

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0003_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerange',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
    ]
