# Generated by Django 3.0.6 on 2020-06-02 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wamytmapp', '0007_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnitDelegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.OrgUnit', verbose_name='Organizational unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='orgunit',
            name='delegates',
            field=models.ManyToManyField(through='wamytmapp.OrgUnitDelegate', to=settings.AUTH_USER_MODEL),
        ),
    ]
