# Generated by Django 3.0.7 on 2020-06-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0008_oudelegates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgunitdelegate',
            options={'permissions': [('assign_delegates', 'Can assign delegates')]},
        ),
    ]
