# Generated by Django 3.0.9 on 2020-08-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0010_history_timeranges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KLogEntry',
        ),
    ]
