# Generated by Django 3.2.9 on 2022-01-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wamytmapp', '0012_auto_20200809_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='odb_org',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mv_odb_org',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='historicaltimerange',
            name='org_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerange',
            name='org_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mit_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
