# Generated by Django 4.0.3 on 2022-03-31 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0013_auto_20220121_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODB_MITARBEITER2STRUKT',
            fields=[
                ('M2O_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('M2O_MIT_ID', models.BigIntegerField()),
                ('M2O_VON', models.DateField()),
            ],
            options={
                'db_table': 'ODB_MITARBEITER2STRUKT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KIND',
            fields=[
                ('kind', models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('m', 'mobile')], max_length=1, primary_key=True, serialize=False)),
                ('wertung', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timerange',
            name='orgunit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.orgunit', verbose_name='Organizational unit'),
        ),
    ]
