# Generated by Django 4.0.3 on 2022-04-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0013_auto_20220121_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='mv_odb_org',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mv_odb_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KIND',
            fields=[
                ('kind', models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('m', 'mobile')], max_length=1, primary_key=True, serialize=False)),
                ('wertung', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MV_OMS_DATEN',
            fields=[
                ('mit_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mit_name_akt', models.CharField(max_length=255, null=True)),
                ('mit_vorname', models.CharField(max_length=255, null=True)),
                ('mit_austritt', models.DateField(blank=True, null=True)),
                ('kid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'mv_oms_daten',
            },
        ),
        migrations.CreateModel(
            name='ODB_MITARBEITER2STRUKT',
            fields=[
                ('m2o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m2o_mit_id', models.BigIntegerField(null=True)),
                ('m2o_org_id', models.IntegerField(null=True)),
                ('m2o_von', models.DateField(blank=True, null=True)),
                ('m2o_bis', models.DateField(blank=True, null=True)),
                ('m2o_typ', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'odb_mitarbeiter2strukt',
            },
        ),
        migrations.CreateModel(
            name='ODB_STRUKT',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_parent_id', models.IntegerField(null=True)),
                ('m_org_id', models.IntegerField(null=True)),
                ('m_von', models.DateField(blank=True, null=True)),
                ('m_bis', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'odb_strukt',
            },
        ),
        migrations.DeleteModel(
            name='odb_org',
        ),
        migrations.RemoveIndex(
            model_name='timerange',
            name='wamytmapp_t_orgunit_f0ecff_idx',
        ),
        migrations.AlterField(
            model_name='timerange',
            name='orgunit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.orgunit', verbose_name='Organizational unit'),
        ),
        migrations.AddIndex(
            model_name='timerange',
            index=models.Index(fields=['org_id', 'start', 'end'], name='wamytmapp_t_org_id_d9026b_idx'),
        ),
    ]
