# Generated by Django 4.0.3 on 2022-04-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0016_data4kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='orgs4wamytm',
            fields=[
                ('ko_m', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wamytmapp.odb_strukt')),
            ],
        ),
    ]
