# Generated by Django 4.0.3 on 2022-04-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0017_orgs4wamytm'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE auth_user add column mit_id int4","ALTER TABLE auth_user DROP column mit_id")
    ]