# Generated by Django 4.0.3 on 2022-05-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0018_add_mitid2auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltimerange',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='timerange',
            name='org_id',
        ),
        migrations.AddField(
            model_name='historicaltimerange',
            name='org',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wamytmapp.odb_org', verbose_name='Organizational unit'),
        ),
        migrations.AddField(
            model_name='timerange',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wamytmapp.odb_org', verbose_name='Organizational unit'),
        ),
    ]
