# Generated by Django 4.0.3 on 2022-05-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0019_remove_historicaltimerange_org_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunitdelegate',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wamytmapp.odb_org'),
        ),
        migrations.AlterField(
            model_name='orgunitdelegate',
            name='orgunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wamytmapp.orgunit', verbose_name='Organizational unit'),
        ),
    ]
