# Generated by Django 4.0.3 on 2022-05-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0020_orgunitdelegate_org_alter_orgunitdelegate_orgunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oms',
            name='mit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timerange',
            name='orgunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.orgunit', verbose_name='Organizational unit'),
        ),
    ]
