# Generated by Django 4.0.6 on 2022-07-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0021_alter_oms_mit_id_alter_timerange_orgunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltimerange',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical time range', 'verbose_name_plural': 'historical time ranges'},
        ),
        migrations.RemoveField(
            model_name='orgs4wamytm',
            name='ko_m',
        ),
        migrations.AddField(
            model_name='orgs4wamytm',
            name='m_org',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wamytmapp.odb_org'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltimerange',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
