# Generated by Django 4.0.6 on 2022-12-01 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wamytmapp', '0022_alter_historicaltimerange_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtualteam',
            fields=[
                ('vt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vt_parent_id', models.IntegerField(null=True)),
                ('vt_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orgs4wamytm',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ma2vt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.virtualteam')),
            ],
        ),
    ]
