# Generated by Django 4.0.6 on 2022-12-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0023_virtualteam_alter_orgs4wamytm_options_ma2vt'),
    ]

    operations = [
        migrations.DeleteModel(name='orgs4wamytm')
    ]
