# Generated by Django 4.0.6 on 2022-12-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0024_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='orgs4wamytm',
            fields=[
                ('m_org', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wamytmapp.odb_org')),
            ],
        ),
    ]
