# Generated by Django 4.0.6 on 2022-12-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0025_orgs4wamytm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ma2vt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
