# Generated by Django 4.0.6 on 2022-12-01 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wamytmapp', '0026_alter_ma2vt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ma2vt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualteam',
            name='vt_name',
            field=models.TextField(),
        ),
    ]
