# Generated by Django 2.2.6 on 2019-10-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.OrgUnit')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.OrgUnit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True)),
                ('kind', models.CharField(choices=[('a', 'absent'), ('p', 'present')], default='a', max_length=1)),
                ('orgunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.OrgUnit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wamytmapp.TeamMember')),
            ],
        ),
    ]
