# Generated by Django 3.0.4 on 2020-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamytmapp', '0006_remove_kinddetail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timerange',
            index=models.Index(fields=['orgunit', 'start', 'end'], name='wamytmapp_t_orgunit_f0ecff_idx'),
        ),
    ]
